version: '3.5'
 
services:
  db:
    image: dahln/private:cdp_db.18.3.13.8
    volumes:
      - /home/dahln/data/db:/data/db
    restart: always

  api:
    image: dahln/private:cdp_api.18.3.13.8
    links:
      - db
    restart: always

  nginx:
    image: dahln/private:cdp_nginx.18.3.13.8  
    links:
      - api
    ports:
      - "80:80"
      - "443:443"
    restart: always