version: '3.5'
 
services:
  db:
    image: dahln/private:cdp_db.18.3.12.4
    restart: always

  api:
    image: dahln/private:cdp_api.18.3.12.4
    restart: always
    links:
      - db
    restart: always

  nginx:
    image: dahln/private:cdp_nginx.18.3.12.4    
    links:
      - api
    ports:
      - "80:80"
    restart: always
