version: '3.5'
 
services:

  api:
    image: damn_api
    build:
      context: .
      dockerfile: ./api.damn/Dockerfile
    restart: always

  proxy:
    image: damn_proxy
    build:
      context: .
      dockerfile: ./proxy.damn/Dockerfile
    links:
      - api
    ports:
    - "80:80"
    - "443:443"
    restart: always