version: '3.5'
 
services:
  db:
    image: mongo
    ports: 
        - 27017:27017
    # volumes:
    #   - /home/dahln/data/db:/data/db
    restart: always

  api:
    image: cdp_api
    build:
      context:  ./api
      dockerfile: Dockerfile
    links:
      - db
    restart: always

  nginx:
    image: cdp_nginx
    build:
      context: ./website/Angular
      dockerfile: Dockerfile
    links:
      - api
    ports:
    - "80:80"
    - "443:443"
    restart: always