version: '3.5'
 
services:
  db:
    image: mongo
    ports: 
        - 27017:27017
    # volumes:
    #   - /home/dahln/data/db:/data/db
    restart: always

  app:
    image: stack_app
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    restart: always

  nginx:
    image: stack_nginx
    build:
      context: ./proxy.stack
      dockerfile: Dockerfile
    links:
      - app
    ports:
    - "80:80"
    - "443:443"
    restart: always
